const icons = {
    mood0: require('@assets/icons/mood0.png'),
    mood1: require('@assets/icons/mood1.png'),
    mood2: require('@assets/icons/mood2.png'),
    mood3: require('@assets/icons/mood3.png'),
    mood4: require('@assets/icons/mood4.png'),
    energy0: require('@assets/icons/energy0.png'),
    energy1: require('@assets/icons/energy1.png'),
    energy2: require('@assets/icons/energy2.png'),
    goal: require('@assets/icons/goal.png'),
    mood: require('@assets/icons/mood.png'),
    point: require('@assets/icons/point.png'),
    settings: require('@assets/icons/settings.png'),
    circleLeft: require('@assets/icons/circleLeft.png'),
    circleRight: require('@assets/icons/circleRight.png'),
    plus: require('@assets/icons/plus.png'),
    streak: require('@assets/icons/streak.png'),
    check: require('@assets/icons/check.png'),
    pen: require('@assets/icons/pen.png'),
    logout: require('@assets/icons/logout.png'),
    refresh: require('@assets/icons/refresh.png'),
    refreshBold: require('@assets/icons/refresh-bold.png'),
    cancel: require('@assets/icons/cancel.png'),
    bin: require('@assets/icons/bin.png'),

    habit: {
        adventure: require('@assets/icons/habit/adventure.png'),
        creativity: require('@assets/icons/habit/creativity.png'),
        diet: require('@assets/icons/habit/diet.png'),
        eco: require('@assets/icons/habit/eco.png'),
        finances: require('@assets/icons/habit/finances.png'),
        fitness: require('@assets/icons/habit/fitness.png'),
        gift: require('@assets/icons/habit/gift.png'),
        health: require('@assets/icons/habit/health.png'),
        hydration: require('@assets/icons/habit/hydration.png'),
        internet: require('@assets/icons/habit/internet.png'),
        learning: require('@assets/icons/habit/learning.png'),
        mindfulness: require('@assets/icons/habit/mindfulness.png'),
        productivity: require('@assets/icons/habit/productivity.png'),
        relationships: require('@assets/icons/habit/relationships.png'),
        selfCare: require('@assets/icons/habit/self-care.png'),
        sleep: require('@assets/icons/habit/sleep.png'),
        time: require('@assets/icons/habit/time.png'),
    },
};

export default icons;
