const icons = {
    mood0: require('@assets/icons/mood0.png'),
    mood1: require('@assets/icons/mood1.png'),
    mood2: require('@assets/icons/mood2.png'),
    mood3: require('@assets/icons/mood3.png'),
    mood4: require('@assets/icons/mood4.png'),
    energy0: require('@assets/icons/energy0.png'),
    energy1: require('@assets/icons/energy1.png'),
    energy2: require('@assets/icons/energy2.png'),
    goal: require('@assets/icons/goal.png'),
    mood: require('@assets/icons/mood.png'),
    point: require('@assets/icons/point.png'),
    settings: require('@assets/icons/settings.png'),
    circleLeft: require('@assets/icons/circleLeft.png'),
    circleRight: require('@assets/icons/circleRight.png'),
    plus: require('@assets/icons/plus.png'),
    streak: require('@assets/icons/streak.png'),
    check: require('@assets/icons/check.png'),
    pen: require('@assets/icons/pen.png'),
    logout: require('@assets/icons/logout.png'),
    login: require('@assets/icons/login.png'),
    refresh: require('@assets/icons/refresh.png'),
    refreshBold: require('@assets/icons/refresh-bold.png'),
    cancel: require('@assets/icons/cancel.png'),
    bin: require('@assets/icons/bin.png'),
    home: require('@assets/icons/home.png'),
    puzzle: require('@assets/icons/puzzle.png'),
    topArrow: require('@assets/icons/top-arrow.png'),
    bottomArrow: require('@assets/icons/bottom-arrow.png'),
    calendarCheck: require('@assets/icons/calendar-check.png'),
    calendarCross: require('@assets/icons/calendar-cross.png'),
    calendarDays: require('@assets/icons/calendar-days.png'),
    eye: require('@assets/icons/eye.png'),
    eyeCrossed: require('@assets/icons/eye-crossed.png'),

    habit: {
        productivity: require('@assets/habit-icons/productivity.png'),
        adventure: require('@assets/habit-icons/adventure.png'),
        creativity: require('@assets/habit-icons/creativity.png'),
        diet: require('@assets/habit-icons/diet.png'),
        eco: require('@assets/habit-icons/eco.png'),
        finances: require('@assets/habit-icons/finances.png'),
        fitness: require('@assets/habit-icons/fitness.png'),
        gift: require('@assets/habit-icons/gift.png'),
        health: require('@assets/habit-icons/health.png'),
        hydration: require('@assets/habit-icons/hydration.png'),
        internet: require('@assets/habit-icons/internet.png'),
        learning: require('@assets/habit-icons/learning.png'),
        mindfulness: require('@assets/habit-icons/mindfulness.png'),
        relationships: require('@assets/habit-icons/relationships.png'),
        selfCare: require('@assets/habit-icons/self-care.png'),
        sleep: require('@assets/habit-icons/sleep.png'),
        time: require('@assets/habit-icons/time.png'),
    },
};

export default icons;
